### PR TITLE
Fixed linker errors on compilation of solver with CMake.

### PR DESCRIPTION
**Pull request by tranqui**

### CODE REVIEW

**Comment by tunnuz** [comment]
Hi @tranqui, thanks for your contribution. I am no longer actively maintaining this, and I'm keen to just accept your changes as they're probably improving the standing of the codebase. Could you summarise for me what changes have been done? I noticed that the PILAL library has been removed (probably for the best), and a different one is being used in place. Is there any any consequence on the licensing of this? Finally, I'd like to know, just out of curiosity, what you're using this for.

**Comment by tranqui** [comment]
Hi @tunnuz, as it turned out I had only intended to submit a pull request for the first commit (which fixes build errors with more recent versions of CMake) which seemed like an uncontroversial change. However, I didn't seem to fully understand how github's pull requests work so my later commits got added also. In hindsight I should have submitted a pull request from a different branch.

I'll try to summarise my changes:
* I've introduced Eigen as the linear algebra. This is a widely used linear algebra library that can be further optimised using BLAS and LAPACK under-the-hood if needed.
* I changed the library so everything is defined through templates, so you can include it through header files entirely. Correspondingly, I made the namespace change optimization -> cpplex to make it more specific and prevent clashes (I use another libraries that has the same "optimization" namespace!). This relies on the change to Eigen.
* I added finer control over the verbosity of iteration output, so you can silence the algorithm if using it as a component in a larger algorithm.
* I noticed that the algorithm failed if the right-hand side of the standard form constraints were negative, so I added a few lines to convert the constraints if negative values were given.
* I added a new example for computing a conical hull over a bunch of vectors (cf. my use-case at the bottom).

You raise a good point about licensing. Eigen is released under the Mozilla Public License (MPL) which is more permissive than the MIT license. I'm not an expert on licensing, but I assume we'd have to repurpose the entire library under MPL to combine the two? It may make more sense to just accept the first commit, and then for me to maintain my own fork under the MPL. If you agree, then I can reverse adding the further commits to master.

My own use-case might provide context for these changes. My research involves using computational geometry to solve physics problems. In my current problem I've found I need to calculate a [conical hull](https://en.wikipedia.org/wiki/Conical_combination); this problem can be reduced to a linear optimisation problem to determine which unit vectors are linearly independent under some constraints. I needed a lightweight C++ code that could be embedded in my application, which is a template header-only library. At some point I plan on releasing my own library publicly, and I will credit you for this component of course.

**Comment by tunnuz** [comment]
That's great, thanks. To be honest, I don't have a strong opinion about the licensing. I choose MIT because it was permissive, but I'm happy to relicense this going forward. I can accept the full pull request, you don't need to split it up, but I do have a request. One aspect that I liked about this codebase is that it was self-contained and didn't depend on anything else. Of course, this was at the expense of performance, as I'm sure Eigen is orders of magnitude better than PILAL. Would it however be possible to include a switch to compile with either? This way people wanting to use this without including additional dependencies could just drop the code in their project.

**Comment by tranqui** [comment]
I think that would be a very cool feature. I can look into putting it in later this week.

It occurs to me my change does not actually include Eigen, it simply assumes you have it installed on your system. As such I think we might not have to change the license. I agree it is better to give users the option to choose which library to use.

**Comment by tranqui** [comment]
I never had the time to do this in the end. Let's just leave the PILAL implementation in the original, and the fork with the Eigen implementation in my repo.

**Pull request closed without merging**
